### ISSUE TITLE
Search Recursively?

### ISSUE THREAD

**Issue by drcxd** [mclear-tools/consult-notes#12]
Can I use an option to specify some particular sources should be searched recursively?

For example, if there is a source directory named `~/notes` and there are some sub-directories in it like `~/notes/books` and `~/notes/journal`. I do not want to set these sources explicitly, since I may create new sub-directories or remove them.

**Comment by mclearc** [comment]
Depending on whether you're using grep or ripgrep you should be able to set the `consult-notes-*grep-args` to ignore the relevant directories. See those variables' default values.

**Comment by drcxd** [comment]
To clarify, what I want is to include these sub-directories recursively , when using the command `consult-notes`.

Assume I have a file structure like this:
```
-- ~/notes
 |-- general-notes.txt
 |-- books
   |-- note1.txt
   |-- note2.txt
 |-- journals
   |-- note3.txt
```
If I set `consult-note-sources` to `~/notes`, and then I issue the command `consult-notes`, the only candidate I get is `general-notes.txt`. Could `consult-notes` search the directory recursively so I could get `note1.txt`, `note2.txt` and `note3.txt` as candidates as well without setting their locating directories explicitly in `consult-note-sources`?

**Comment by mclearc** [comment]
If by "search" you mean merely filename and info then no it is not recursive, since part of the point of consult-notes is to allow you to narrow to a notes source by key, and to show each notes source as part of completing read in cosult-multi.  On the other hand if you want to search *in notes* (and not just for file name) then that may be done recursively.
