### ISSUE TITLE
preview-key issue

### ISSUE THREAD

**Issue by basaran** [mclear-tools/consult-notes#15]
Hello,

I'm not sure if this is specific to denote, or consult itself, but for some reason, I am not seeing live preview of the notes?

Normally, I would expect this to give previews during selections

```elisp
(defun fake-notes (&optional sources)
  "Find a file in a notes directory with consult-multi, or from SOURCES."
  (interactive)
  (consult-notes--make-all-sources)
  (let* ((consult--buffer-display #'switch-to-buffer)
         (selected (consult--multi (or sources consult-notes--all-sources)
                                  :require-match
                                  (confirm-nonexistent-file-or-buffer)
                                  :prompt "potes: "
                                  :preview-key 'any
                                  :history 'consult-notes-history
                                  :sort nil)))
    ;; For non-matching candidates, fall back to buffer-file creation.
    (unless (plist-get (cdr selected) :match)
      (consult--file-action (car selected)))))

```

If you could provide some insight, I will surely appreciate it.

**Comment by mclearc** [comment]
I don't tend to use the live-preview aspect of consult, so I actually hadn't noticed this. But my sense is that live-preview isn't offered by consult for all functions it employs. And since `consult-notes` uses `directory-files` (which just lists file names in a directory) to list notes, no previews are offered.

**Comment by basaran** [comment]
Thank you, I will keep looking. Let's close this for now.

**Comment by mclearc** [comment]
Please do let me know if this turns out otherwise and I'll make changes accordingly.

**Comment by mclearc** [comment]
Hi @basaran, turns out I was wrong and it is possible to preview notes using the standard `consult-notes` function. See https://github.com/mclear-tools/consult-notes/commit/3c73e4f6056ce938f9b9f554970f990c0b256538. This will work if you're just using consult with directories of notes. I need to write custom preview functions for `consult-notes-denote` and `consult-notes-org-roam` minor modes. I hope to get that taken care of in the nearish future.
