### ISSUE TITLE
Annotations do not display in narrower screen

### ISSUE THREAD

**Issue by whhone** [mclear-tools/consult-notes#22]
See the attached screenshot:

![Screenshot 2022-12-06 18 52 50](https://user-images.githubusercontent.com/1200104/206076492-c8df3e9b-c154-4984-bafb-cf360b955622.png)

**Comment by whhone** [comment]
Still the same. It seems that a few long file names can pushed all annotations to the very right.

**Comment by whhone** [comment]
On my laptop, (window-total-width) => 144 (#o220, #x90). Is it too small?

Also, I have some files (filtered by search keywords from the above screenshot) with much much longer file names.

**Comment by mclearc** [comment]
at (window-total-width) = 133 I don't see any truncation. But if it gets much smaller things start to get pushed off. Perhaps I could truncate the titles after a certain length. Do you see the same problem when using the consult-notes denote minor mode?

**Comment by whhone** [comment]
Using denote minor mode:

This is my laptop screen (smaller)
![Screenshot 2022-12-06 19 57 34](https://user-images.githubusercontent.com/1200104/206084719-b02477bd-5791-44af-8771-5d7c4bd82173.png)

Moving to a another screen (smaller)
![Screenshot 2022-12-06 19 57 07](https://user-images.githubusercontent.com/1200104/206084729-3a863090-20eb-4d0f-be97-03b54e956bf7.png)

**Comment by mclearc** [comment]
Hmmm -- I'll see about truncating the candidate, but you might also try `(setq marginalia-align 'left)` and see if that helps.

**Comment by mclearc** [comment]
For denote integration you might consider hiding the id with `consult-notes-denote-display-id` set to `nil`. As for further truncation I'm not inclined to include this since there are issues with completion candidates being hidden by the truncation. See the discussions [here](https://github.com/minad/marginalia/issues/145) and [here](https://github.com/minad/vertico/issues/198), as well as the wiki discussion [here](https://github.com/minad/vertico/wiki#left-truncate-recentf-filename-candidates-eg-for-consult-buffer). If you tend to have such very long titles you might try adding advice to the candidate display.
