### ISSUE TITLE
limit search to text and code type files?

### ISSUE THREAD

**Issue by JonatanSahar** [mclear-tools/consult-notes#34]
I keep screen captures in org mode files in a way that produces an image file in the same dir and then inserts a link to it into the file.
When running `consult-notes` I find these image files in the list of notes displayed. 
I think it's would be a good idea to add an ignore-filetypes-list (or a whitelist, conversly) to limit to scope of files displayed.

**Comment by mclearc** [comment]
Are you using denote? Take a look at the variable `consult-notes-denote-files-function`, which you can set to `(denote-directory-text-only-files)` to exclude images. 

Otherwise, the `consult-notes` function uses `(directory-files)` and includes the custom variable `consult-notes-file-match`, which is a regex pattern for filtering out filetypes that don't match the regex. Adjust the variable as you like to exclude images.

**Comment by JonatanSahar** [comment]
Ah, nice, that's great. Thanks!
