### ISSUE TITLE
subdirectories

### ISSUE THREAD

**Issue by oatmealm** [mclear-tools/consult-notes#47]
My denote-directory has possibly 3 level deep-nesting, i.e. ~/Document/notes/references/uuid-per-document/
When I try to activate consult-notes with setup using `consult-notes-denote-mode`, I'm seeing this error: `Read error: Is a directory, ~/Documents/notes/references/20230828T084007`. When I set the directories manually, it seems to work. 

```
(use-package! consult-notes
  :commands (consult-notes)
  :config
  ;; (consult-notes-denote-mode)
  (setq consult-notes-file-dir-sources
        `(("References" ?b "~/Documents/notes/references"))))

```

**Comment by mclearc** [comment]
Sorry for the very late reply. You need to set the file sources for consult-notes to function. `consult-notes-denote-mode` will add your denote dir to the list of sources automatically. Do you have that set as `~/Documents/notes/references` and is the Denote variable loaded before you've loaded consult-notes?

**Comment by grszkthfr** [comment]
I had the same / a similar issue here.

I am using `(consult-notes-denote-mode)` and I can reproduce the error when I create a subfolder with a name that is also a "valid" denote ID, e.g. a folder named "20231206T084027" in a subdirectory produces the following error:

`progn: Read error: Is a directory, xxx/denote/2023/20231206T084027`

This happend when I was reusing the denote ID for my attachment folders. 

Now my attachment folders are named `yyyy/mmddThhmmss`, or in the example above "xxx/denote/2023/1206T084027". As such they can't easily be mistaken for a denote ID and everything is working as expected.

So my guess here is that consult-notes mistakenly tries to read the folder as a note!?

**Comment by mclearc** [comment]
> So my guess here is that consult-notes mistakenly tries to read the folder as a note!?

`(consult-notes-denote--source)` is a construction that relies on individuating notes by their id, which it gets using `(denote-filename-identifier)`. So it assumes that each file has a unique identifier (as does denote). So I suspect that this is what was causing the trouble. There may be a way to get around that but I'm not inclined to try and account for the case since denote assumes (correctly I think) by default that all elements in a denote dir have a unique identifier. It seems like you have resolved the issue for yourself though.

**Comment by grszkthfr** [comment]
> It seems like you have resolved the issue for yourself though.

Indeed. Although for aesthetic reasons. 😁

But your reasoning totally makes sense.
